on:
    push:
        branches:
            main

jobs:
    build-all:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@v7
              with: 
                node-version: 24
            - run: cd apps/backend
            - run: cd npm ci
            - run: npm run build
            - run: npm run test
            - run: npm run start